### ISSUE TITLE
Can't install on Laravel 10

### ISSUE THREAD

**Issue by rstanislav** [alexstewartja/laravel-attribute-observer#6]
Hello!
On laravel 10 composer require alexstewartja/laravel-attribute-observer results in 
Problem 1
    - alexstewartja/laravel-attribute-observer[1.0.0, ..., 1.0.2] require illuminate/contracts ^8.37 -> found illuminate/contracts[v8.37.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - alexstewartja/laravel-attribute-observer[1.0.3, ..., 1.2.1] require illuminate/contracts ^7.0|^8.0 -> found illuminate/contracts[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - alexstewartja/laravel-attribute-observer[1.3.0, ..., 1.4.3] require illuminate/contracts ^7.0|^8.0|^9.0 -> found illuminate/contracts[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires alexstewartja/laravel-attribute-observer * -> satisfiable by alexstewartja/laravel-attribute-observer[1.0.0, ..., 1.4.3].

On laravel 10 there is no  illuminate/contracts package, tried to install it, but nothing changed..
Can't figure out whats wrong, can you help me please ?

**Comment by alexstewartja** [comment]
@rstanislav Issue resolved. v1.4.5 has been released with compatibility for Laravel v10.x
